
server:
  port: 8888

spring:
  application:
    name: TI_Social-Network
  #    database
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    url:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
