
server:
  port: 8888

spring:
  application:
    name: TI_Social-Network
  #    database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/ti_social_network
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  flyway:
    locations: classpath:/db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

application:
  origin:
    fe-url: http://localhost:5173
  cloudinary:
    cloud-name: dunemoydy
    api-key: 451832414779783
    api-secret: -1Vt1j9Q4Kjyf9mWYOTM5XGggoI
  security:
    jwt:
      secret-key: bb49931b1b6e4cd6529c2f21bcbce342c46d5dfe6b8b829237dceff8afb4d1cf
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days




